### ISSUE TITLE
明日の天気とか、１週間の天気が表示される機能が欲しい

### ISSUE THREAD

**Issue by yuki9431** [yuki9431/myLinebot#21]

**Comment by kfymr** [comment]
前日の夜寝る前に知っておけたら便利ですね！

**Comment by yuki9431** [comment]
それはいいb
起床時間と就寝時間が人それぞれだから、個別に通知タイミングを設定できたらベストなんやけど....
実装が大変><

**Comment by kfymr** [comment]
尋ねたら答えるようにすむなら簡単かな？
普通に検索するのとまるで変わらんけど

**Comment by yuki9431** [comment]
それはすぐ実装できるかな、
"明日"って言葉に反応して明日の天気だすようにするわ

自分でチケット書いといてあれやけど、無料アカウントだと
3日分の天気しか取得できないから、1週間は無理だったという
